[workspace]
authors = ["AimPizza <rickomo.us@gmail.com>"]
channels = ["conda-forge"]
name = "stylix-previewer"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
textual = ">=6.10.0,<7"
