[workspace]
authors = ["AimPizza <rickomo.us@gmail.com>"]
channels = ["conda-forge"]
name = "stylix-previewer"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
code = "code ."
start = "python src/main.py"
watch = "textual run --dev src/main.py"

[dependencies]
textual = ">=6.10.0,<7"
textual-dev = ">=1.8.0,<2"
pyperclip = ">=1.11.0,<2"
pyyaml = ">=6.0.3,<7"
